import {
	Attribute,
	Execution,
	Range,
	SheetForm,
	Size,
	SkillName,
	SpellCircle,
	SpellSchool,
	SpellType,
} from './types';

export const attributes: Attribute[] = [
	'DES',
	'FOR',
	'CON',
	'INT',
	'SAB',
	'CAR',
];

export const sizes: Size[] = [
	'Minúsculo',
	'Pequeno',
	'Médio',
	'Grande',
	'Enorme',
	'Colossal',
];

export const executions: Execution[] = [
	'Completa',
	'Livre',
	'Movimento',
	'Padrão',
	'Reação',
];

export const ranges: Range[] = ['Pessoal', 'Toque', 'Curto', 'Médio', 'Longo'];

export const spellSchools: SpellSchool[] = [
	'Abjuração',
	'Adivinhação',
	'Convocação',
	'Encantamento',
	'Evocação',
	'Ilusão',
	'Necromancia',
	'Transmutação',
];

export const spellCircles: SpellCircle[] = [
	'1º Círculo',
	'2º Círculo',
	'3º Círculo',
	'4º Círculo',
	'5º Círculo',
];

export const spellTypes: SpellType[] = ['Arcana', 'Divina', 'Universal'];

export const skillNames: SkillName[] = [
	'acrobatics',
	'animal_handling',
	'athletics',
	'performance',
	'ride',
	'knowledge',
	'heal',
	'diplomacy',
	'deception',
	'fortitude',
	'stealth',
	'warfare',
	'initiative',
	'intimidation',
	'intuition',
	'investigation',
	'gambling',
	'thievery',
	'fighting',
	'mysticism',
	'nobility',
	'perception',
	'driving',
	'aim',
	'reflexes',
	'religion',
	'survival',
	'will',
];

export const sheetFormInitialState: SheetForm = {
	mode: 'create',
	character: '',
	player: '',
	race: '',
	origin: '',
	class: '',
	divinity: '',
	level: '',
	attributes: {
		DES: '',
		FOR: '',
		CON: '',
		INT: '',
		SAB: '',
		CAR: '',
	},
	lp: {
		total: '',
		actual: '',
	},
	mp: {
		total: '',
		actual: '',
	},
	skills: [
		{
			name: 'Acrobacia',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
			armour_penalty: true,
		},
		{
			name: 'Adestramento',
			trained: false,
			attribute: 'CAR',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Atletismo',
			trained: false,
			attribute: 'FOR',
			bonus_others: '',
		},
		{
			name: 'Atuação',
			trained: false,
			attribute: 'CAR',
			bonus_others: '',
		},
		{
			name: 'Cavalgar',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
		},
		{
			name: 'Conhecimento',
			trained: false,
			attribute: 'INT',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Cura',
			trained: false,
			attribute: 'SAB',
			bonus_others: '',
		},
		{
			name: 'Diplomacia',
			trained: false,
			attribute: 'CAR',
			bonus_others: '',
		},
		{
			name: 'Enganação',
			trained: false,
			attribute: 'CAR',
			bonus_others: '',
		},
		{
			name: 'Fortitude',
			trained: false,
			attribute: 'CON',
			bonus_others: '',
		},
		{
			name: 'Furtividade',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
			armour_penalty: true,
		},
		{
			name: 'Guerra',
			trained: false,
			attribute: 'INT',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Iniciativa',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
		},
		{
			name: 'Intimidação',
			trained: false,
			attribute: 'CAR',
			bonus_others: '',
		},
		{
			name: 'Intuição',
			trained: false,
			attribute: 'SAB',
			bonus_others: '',
		},
		{
			name: 'Investigação',
			trained: false,
			attribute: 'INT',
			bonus_others: '',
		},
		{
			name: 'Jogatina',
			trained: false,
			attribute: 'CAR',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Ladinagem',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
			trained_only: true,
			armour_penalty: true,
		},
		{
			name: 'Luta',
			trained: false,
			attribute: 'FOR',
			bonus_others: '',
		},
		{
			name: 'Misticismo',
			trained: false,
			attribute: 'INT',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Nobreza',
			trained: false,
			attribute: 'INT',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Percepção',
			trained: false,
			attribute: 'SAB',
			bonus_others: '',
		},
		{
			name: 'Pilotagem',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Pontaria',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
		},
		{
			name: 'Reflexos',
			trained: false,
			attribute: 'DES',
			bonus_others: '',
		},
		{
			name: 'Religião',
			trained: false,
			attribute: 'SAB',
			bonus_others: '',
			trained_only: true,
		},
		{
			name: 'Sobrevivência',
			trained: false,
			attribute: 'SAB',
			bonus_others: '',
		},
		{
			name: 'Vontade',
			trained: false,
			attribute: 'SAB',
			bonus_others: '',
		},
		{
			name: 'Ofício',
			title: '',
			trained: false,
			attribute: 'INT',
			bonus_others: '',
			trained_only: true,
		},
	],
	attacks: [
		{
			name: 'Desarmado',
			test: 'Luta',
			damage: '1d3+FOR',
			critical: '20',
			type: 'Impacto',
			range: '-',
		},
		{
			name: '',
			test: '',
			damage: '',
			critical: '',
			type: '',
			range: '',
		},
	],
	defense: {
		attribute: 'DES',
		bonus_others: '',
		damage_reduction: '',
		armor: {
			name: '',
			value: '',
			penalty: '',
		},
		shield: {
			name: '',
			value: '',
			penalty: '',
		},
		should_sum_modifier: true,
	},
	experience_points: '',
	proficiencies: '',
	size: 'Médio',
	movement: '',
	equipments: [
		{
			name: '',
			weight: '',
		},
	],
	tibar: {
		regular: '',
		gold: '',
	},
	abilities: {
		race: [],
		class: [],
		origin: [],
		general: [],
		spell: [],
	},
	spell_modifier: 'INT',
	spell_resistance: '',
	description: '',
	notes: '',
	total_weight: '10',
};
